### PR TITLE
feat: rules page added

### PR DESCRIPTION
**Pull request by vrx29**
Live Preview : https://gimesto-quiz.netlify.app/pages/rules.html

Created rules page for Quiz App : This page contains quiz-card which will display all the rules to be followed while playing the quiz.

Screenshot 2022-02-13 at 10 11 56 PM

### CODE REVIEW

**Review by partha8 — APPROVED** [review]
Looks good! and cool UI

Also, quiz-card/quiz-cont is a little misleading here. You can keep it as rules-card.

**Review by foolhardy21 — APPROVED** [review]
looks good to merge

**Comment by vrx29** [comment]
> 

Actually I am using these names as this will be used for displaying quiz and quiz results as well.

**Comment by partha8** [comment]
> > 
> 
> Actually I am using these names as this will be used for displaying quiz and quiz results as well.

Okay, got it!

**Comment by vrx29** [comment]
> 

@partha8 Actually I am using these names because this same card will be used for displaying quiz questions as well on the same card. Will look for something common and try to replace it.

**Pull request merged**
